Kisisel_Web_Projesi/Models/Class/Admin.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Kisisel_Web_Projesi.Models.Class
{
    public class Admin
    {
        [Key]
        public int id { get; set; }
        public string kullaniciadi { get; set; }
        public string sifre { get; set; }
    }
}

Kisisel_Web_Projesi/Models/Class/AnaSayfa.cs
using System.ComponentModel.DataAnnotations;

namespace Kisisel_Web_Projesi.Models.Class
{
    public class AnaSayfa
    {
        [Key]
        public int id { get; set; }
        public string profil { get; set; }
        public string isim { get; set; }
        public string unvan { get; set; }
        public string aciklama { get; set; }
        public string iletisim { get; set; }
    }
}

Kisisel_Web_Projesi/Models/Class/Context.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;

namespace Kisisel_Web_Projesi.Models.Class
{
    public class Context:DbContext
    {
        public DbSet<Admin> Admins { get; set; }
        public DbSet<AnaSayfa> AnaSayfas { get; set; }
        public DbSet<ikonlar> ikonlars { get; set; }
    }
}

Kisisel_Web_Projesi/Models/Class/ikonlar.cs
using System.ComponentModel.DataAnnotations;


namespace Kisisel_Web_Projesi.Models.Class
{
    public class ikonlar
    {
        [Key]
        public int id { get; set; }
        public string ikon { get; set; }
        public string link { get; set; }
    }
}

Kisisel_Web_Projesi/Controllers/AdminController.cs
using Kisisel_Web_Projesi.Models.Class;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Kisisel_Web_Projesi.Controllers
{
    public class AdminController : Controller
    {
        // GET: Admin
        Context c = new Context();
        [Authorize]
        public ActionResult Index()
        {
            var deger = c.AnaSayfas.ToList();
            return View(deger);
        }

        public ActionResult AnaSayfaGetir(int id)
        {
            var ag = c.AnaSayfas.Find(id);
            return View("AnaSayfaGetir", ag);
        }
        public ActionResult AnaSayfaGuncelle(AnaSayfa x)
        {
            var ag = c.AnaSayfas.Find(x.id);
            ag.isim = x.isim;
            ag.profil = x.profil;
            ag.unvan = x.unvan;
            ag.aciklama = x.aciklama;
            ag.iletisim = x.iletisim;
            c.SaveChanges();
            return RedirectToAction("Index");

        }
        public ActionResult ikonListesi() {
            var deger = c.ikonlars.ToList();
            return View(deger);
        }

        //yeni ikonlar
        [HttpGet]
        public ActionResult YeniIkon()
        {
            return View();
     
        }

        [HttpPost]
        public ActionResult YeniIkon (ikonlar p)
        {
            c.ikonlars.Add(p);
            c.SaveChanges();
            return RedirectToAction("ikonListesi");
        }
        public ActionResult ikonGetir(int id)
        {
            var ig = c.ikonlars.Find(id);
            return View("ikonGetir", ig);
        }

        public ActionResult ikonGuncelle(ikonlar x)
        {
            var ig = c.ikonlars.Find(x.id);
            ig.ikon = x.ikon;
            ig.link = x.link;
            c.SaveChanges();
            return RedirectToAction("ikonListesi");
        }
        public ActionResult ikonSil(int id)
        {
            var sl = c.ikonlars.Find(id);
            c.ikonlars.Remove(sl);
            c.SaveChanges();
            return RedirectToAction("ikonListesi");
        }
    }
}

Kisisel_Web_Projesi/Controllers/AnaSayfaController.cs
using Kisisel_Web_Projesi.Models.Class;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Kisisel_Web_Projesi.Controllers
{
    public class AnaSayfaController : Controller
    {
        // GET: AnaSayfa
        Context c = new Context();
        public ActionResult Index()
        {
            var deger= c.AnaSayfas.ToList();
            return View(deger);
        }

        public PartialViewResult ikonlar()
        {
            var deger = c.ikonlars.ToList();
            return PartialView(deger);
        }
    }
}

Kisisel_Web_Projesi/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Kisisel_Web_Projesi.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

Kisisel_Web_Projesi/Controllers/LoginController.cs
using Kisisel_Web_Projesi.Models.Class;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;

namespace Kisisel_Web_Projesi.Controllers
{
    public class LoginController : Controller
    {
        // GET: Login
        Context c = new Context();
    
        public ActionResult Index()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Index(Admin ad)
        {
            var bilgiler = c.Admins.FirstOrDefault(x => x.kullaniciadi == ad.kullaniciadi && x.sifre == ad.sifre);
            if (bilgiler != null)
            {
                FormsAuthentication.SetAuthCookie(bilgiler.kullaniciadi, false);
                Session["kullaniciadi"] = bilgiler.kullaniciadi.ToString();
                return RedirectToAction("Index", "Admin");
            }
            else { return View(); }
        }

    
    public ActionResult LogOut()
    {
        FormsAuthentication.SignOut();
            return RedirectToAction("Index", "Login");

    }
}
}

Kisisel_Web_Projesi/Views/Admin/AnaSayfaGetir.cshtml
@model Kisisel_Web_Projesi.Models.Class.AnaSayfa
@{
    ViewBag.Title = "AnaSayfaGetir";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h2 class="mt-4">Ana Sayfa Güncelle</h2>
<hr />

@using (Html.BeginForm("AnaSayfaGuncelle", "Admin", FormMethod.Post))
{
    @Html.LabelFor(x => x.id)
    @Html.TextBoxFor(x => x.id, new { @class = "form-control", @readonly = "readonly" })
    <br />
    @Html.LabelFor(x => x.isim)
    @Html.TextBoxFor(x => x.isim, new { @class = "form-control" })
    <br />
    @Html.LabelFor(x => x.profil)
    @Html.TextBoxFor(x => x.profil, new { @class = "form-control" })
    <br />
    @Html.LabelFor(x => x.aciklama)
    @Html.TextBoxFor(x => x.aciklama, new { @class = "form-control" })
    <br />
    @Html.LabelFor(x => x.iletisim)
    @Html.TextBoxFor(x => x.iletisim, new { @class = "form-control" })
    <br />
    @Html.LabelFor(x => x.unvan)
    @Html.TextBoxFor(x => x.unvan, new { @class = "form-control" })
    <br />
    <button class="btn btn-success">
        Ana Sayfa Güncelle
    </button>

}

Kisisel_Web_Projesi/Views/Admin/Index.cshtml
@using Kisisel_Web_Projesi.Models.Class
@model List<AnaSayfa>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h2>Ana Sayfa</h2>

<table border="1" width="100%">
    <tr>
        <th>Id</th>
        <th>İsim</th>
        <th>Güncelle</th>
    </tr>
    @foreach (var x in Model)
    {
        <tr>
            <td>@x.id</td>
            <td>@x.isim</td>
            <td><a href="/Admin/AnaSayfaGetir/@x.id" class="btn btn-primary">Güncelle</a></td>
        </tr>
    }

</table>

Kisisel_Web_Projesi/Views/Admin/YeniIkon.cshtml
@model Kisisel_Web_Projesi.Models.Class.ikonlar
@{
    ViewBag.Title = "YeniIkon";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h2>Yeni Ikon Ekle</h2>
<br/>
<form class="form-group" method="post">
    @Html.LabelFor(x => x.ikon)
    @Html.TextBoxFor(x => x.ikon, new { @class = "form-control" })
    <br />
    @Html.LabelFor(x => x.link)
    @Html.TextBoxFor(x => x.link, new { @class = "form-control" })
    <br />
    <button class="btn btn-success">İkon Ekle</button>
</form>

Kisisel_Web_Projesi/Views/Admin/ikonGetir.cshtml
@model Kisisel_Web_Projesi.Models.Class.ikonlar
@{
    ViewBag.Title = "ikonGetir";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h2>ikon Güncelle</h2>
<br />

@using (Html.BeginForm("ikonGuncelle", "Admin", FormMethod.Post))
{
    @Html.LabelFor(x => x.id)
    @Html.TextBoxFor(x => x.id, new { @class = "form-control" })
    <br />
    @Html.LabelFor(x => x.ikon)
    @Html.TextBoxFor(x => x.ikon, new { @class = "form-control" })
    <br />
    @Html.LabelFor(x => x.link)
    @Html.TextBoxFor(x => x.link, new { @class = "form-control" })
    <br />
    <button class="btn btn-success">İkon Güncelle</button>



}

Kisisel_Web_Projesi/Views/Admin/ikonListesi.cshtml
@{
    ViewBag.Title = "ikonListesi";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}
<h2 class="mb-4">İkonlar Sayfası</h2>
<table border width="100%">
    <tr>
        <th>Id</th>
        <th>İkon</th>
        <th>Güncelle</th>
        <th>Sil</th>
    </tr>
    @foreach (var x in Model)
    {
        <tr>
            <td>@x.id</td>
            <td><i class="@x.ikon"></i></td>
            <td><a href="/Admin/ikonGetir/@x.id" class="btn btn-primary">Güncelle</a></td>
            <td><a href="/Admin/ikonsil/@x.id" class="btn btn-danger">Sil</a></td>
            <td></td>
        </tr>
    }
</table>
<a href="/Admin/YeniIkon" class="btn btn-primary">Yeni İkon Ekle</a>

Kisisel_Web_Projesi/Views/AnaSayfa/Index.cshtml
@using Kisisel_Web_Projesi.Models.Class
@model List<AnaSayfa>
@{
    Layout = null;
}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Kişisel Web Sitesi</title>
    <link rel="stylesheet" href="~/web-Kisisel-Sitesi/style.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.2/css/all.min.css">
</head>
<body>
    <div class="center">
        <div class="avatar">
            @foreach (var x in Model)
            {
                <img src="@x.profil">
            }
        </div>
        <div class="content">
            @foreach (var x in Model)
            {
                <h1>@x.isim</h1>
                <h2>@x.unvan</h2>
                <p>@x.aciklama</p>
                <h3>@x.iletisim</h3>
            }

        </div>
        @Html.Action("ikonlar", "AnaSayfa")
    </div>
</body>
</html>

Kisisel_Web_Projesi/Views/AnaSayfa/ikonlar.cshtml
@using Kisisel_Web_Projesi.Models.Class
@model List<ikonlar>

<div class="social">
    @foreach(var x in Model)
            {
              <a href="@x.link"><i class="@x.ikon"></i></a>
            }
    
  
</div>

Kisisel_Web_Projesi/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<main aria-labelledby="title">
    <h2 id="title">@ViewBag.Title.</h2>
    <h3>@ViewBag.Message</h3>

    <p>Use this area to provide additional information.</p>
</main>

Kisisel_Web_Projesi/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<main aria-labelledby="title">
    <h2 id="title">@ViewBag.Title.</h2>
    <h3>@ViewBag.Message</h3>

    <address>
        One Microsoft Way<br />
        Redmond, WA 98052-6399<br />
        <abbr title="Phone">P:</abbr>
        425.555.0100
    </address>

    <address>
        <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
        <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
    </address>
</main>

Kisisel_Web_Projesi/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<main>
    <section class="row" aria-labelledby="aspnetTitle">
        <h1 id="title">ASP.NET</h1>
        <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
        <p><a href="https://asp.net" class="btn btn-primary btn-md">Learn more &raquo;</a></p>
    </section>

    <div class="row">
        <section class="col-md-4" aria-labelledby="gettingStartedTitle">
            <h2 id="gettingStartedTitle">Getting started</h2>
            <p>
                ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
                enables a clean separation of concerns and gives you full control over markup
                for enjoyable, agile development.
            </p>
            <p><a class="btn btn-outline-dark" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
        </section>
        <section class="col-md-4" aria-labelledby="librariesTitle">
            <h2 id="librariesTitle">Get more libraries</h2>
            <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
            <p><a class="btn btn-outline-dark" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
        </section>
        <section class="col-md-4" aria-labelledby="hostingTitle">
            <h2 id="hostingTitle">Web Hosting</h2>
            <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
            <p><a class="btn btn-outline-dark" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
        </section>
    </div>
</main>

Kisisel_Web_Projesi/Views/Login/Index.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Admin Panel Login</title>
    <link rel="stylesheet" href="~/web-Admin-Login/style1.css">

</head>
<body>
    <div class="container">
        <div class="contact-form">
            <img src="~/web-Admin-Login/admin.png" class="admin-img">
            <h2>Admin Login</h2>
            @using (Html.BeginForm("Index", "Login", FormMethod.Post))
            {
                <div class="txtb">
                    <input type="text" name="kullaniciadi" placeholder="Username">
                </div>
                <div class="txtb">
                    <input type="password" name="sifre" placeholder="Password">
                    <input type="submit" class="logbtn" value="Login">
                </div>
            }
        </div>
    </div>
</body>
</html>

Kisisel_Web_Projesi/Views/Shared/_AdminLayout.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>
<html>
<head>
    <title>Admin Panel</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
    <link rel="stylessheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.2/css/all.min.css">
</head>
    <body>

        <!-- Sidebar -->
        <div class="w3-sidebar w3-light-grey w3-bar-block" style="width:25%">
            <h3 class="w3-bar-item">Admin Panel</h3>
            <a href="/Admin/Index" class="w3-bar-item w3-button">Ana Sayfa</a>
            <a href="/Admin/ikonListesi" class="w3-bar-item w3-button">ikonlar</a>
            <a href="/AnaSayfa/Index" target="_blank" class="w3-bar-item w3-button btn-info ">Siteye Git</a>
            <a href="/Login/LogOut" class="w3-bar-item w3-button btn-danger">Çıkış</a>
        </div>

        <!-- Page Content -->
        <div style="margin-left:25%">

            <div class="w3-container" style="background-image: linear-gradient(120deg, pink, rgb(209, 101, 101));">
                <h1 style="color:white">Kişisel Web Sitesi</h1>
            </div>

            <div class="w3-container">
                @RenderBody()

            </div>

    </body>
</html>

Kisisel_Web_Projesi/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark">
        <div class="container">
            @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            <button type="button" class="navbar-toggler" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" title="Toggle navigation" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse d-sm-inline-flex justify-content-between">
                <ul class="navbar-nav flex-grow-1">
                    <li>@Html.ActionLink("Home", "Index", "Home", new { area = "" }, new { @class = "nav-link" })</li>
                    <li>@Html.ActionLink("About", "About", "Home", new { area = "" }, new { @class = "nav-link" })</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home", new { area = "" }, new { @class = "nav-link" })</li>
                </ul>
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>